# Generated by Django 4.1.1 on 2023-11-21 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('is_contestant', models.BooleanField(default=False)),
                ('tokens', models.IntegerField(default=0)),
            ],
        ),
    ]
